// <auto-generated />
using LocalApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LocalApi.Migrations
{
    [DbContext(typeof(LocalApiContext))]
    [Migration("20220909182842_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("LocalApi.Models.Local", b =>
                {
                    b.Property<int>("LocalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Blerb")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000) CHARACTER SET utf8mb4");

                    b.Property<string>("Cuisine")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50) CHARACTER SET utf8mb4");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50) CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50) CHARACTER SET utf8mb4");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.HasKey("LocalId");

                    b.ToTable("Locals");

                    b.HasData(
                        new
                        {
                            LocalId = 1,
                            Blerb = "Vietnamese food, hands down the best. From their boa to the Banh Mi, Mama Dut has some of the best food in town",
                            Cuisine = "Vietnamese",
                            Location = "1414 SE Morrison St, Portland OR, 97214",
                            Name = "Mama Dut",
                            Rating = 10
                        },
                        new
                        {
                            LocalId = 2,
                            Blerb = "This restuarant is whack AF. Food is over salted, under seasoned and overly greasy. Their Insta pics look like someone made sick between two burger buns and decided to post it",
                            Cuisine = "American Classic",
                            Location = "5052 SE Foster Rd, Portland Or, 97206",
                            Name = "Vegan Junk Food",
                            Rating = 1
                        },
                        new
                        {
                            LocalId = 3,
                            Blerb = "As far as i know, the only Sri Lanken restaraunt in Portland, making them the best. Employee owned with great food. food is spicy, so not for the weak willed",
                            Cuisine = "Sri Lanken",
                            Location = "2420 SE Belmont st, Portland Or, 97214",
                            Name = "Mirisata",
                            Rating = 8
                        },
                        new
                        {
                            LocalId = 4,
                            Blerb = "the best vegan texmex in town. Queer owned, all welcoming. Food is out of this world delicious with TexMex Classics like the California Burrito, Chimichangas, nachoes, and the list goes on. a must stop",
                            Cuisine = "Tex/Mex",
                            Location = "1670 NE Killinsworth st, Portland OR, 97211",
                            Name = "Mis Tacones",
                            Rating = 10
                        },
                        new
                        {
                            LocalId = 5,
                            Blerb = "Fresh Bagels and has all of the classic Jewish Deli fair, but Vegan! I dream of the Black and White cookies and 'corned beef' sandwhiches",
                            Cuisine = "Jewish Deli",
                            Location = "1800 NE Alberta St, Portland OR 97211",
                            Name = "Ben & Esther's Vegan Jewish Deil",
                            Rating = 8
                        },
                        new
                        {
                            LocalId = 6,
                            Blerb = "this was dope af, amazing food. Only Open for Brunch/Lunch",
                            Cuisine = "Classic American",
                            Location = "6526 SE Foster Rd, Portland OR 97206",
                            Name = "Off The Griddle",
                            Rating = 8
                        },
                        new
                        {
                            LocalId = 7,
                            Blerb = "Best Donuts in PDX. Exciting flavors that change monthly, to keep things fresh. Their made in house ice cream is great too!",
                            Cuisine = "Donuts",
                            Location = "4110 NE Sandy Blvd, Portland OR 97212",
                            Name = "Doe Donuts",
                            Rating = 9
                        },
                        new
                        {
                            LocalId = 8,
                            Blerb = "Good Pizzas, flat crust, exciting flavors",
                            Cuisine = "Pizza",
                            Location = "1126 SE Division St #200, Portland OR 97202",
                            Name = "Virtuous Pie",
                            Rating = 6
                        },
                        new
                        {
                            LocalId = 9,
                            Blerb = "their 'steak and cheeze' is the best in PDX. Great online presence and thier other sandwiches are great too",
                            Cuisine = "American Classic/Deli",
                            Location = "5026 SE Division St, Portland OR 97206",
                            Name = "DC Vegetarian",
                            Rating = 9
                        },
                        new
                        {
                            LocalId = 10,
                            Blerb = "this is a little different, since it is mostly an all vegan grocer, but they do sell and make fresh hotdogs",
                            Cuisine = "HotDog",
                            Location = "4138 SE 42nd Ave, Portland OR 97206",
                            Name = "Cutie Buys",
                            Rating = 9
                        },
                        new
                        {
                            LocalId = 11,
                            Blerb = "A pretty good standard for vegan food. burger, salads, sandwiches and finger foods. all good",
                            Cuisine = "Chain restaraunt",
                            Location = "508 SW Taylor St, Portland OR 97204",
                            Name = "Veggie Grill",
                            Rating = 7
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
